// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGnrcIEVU-p0W7mygzipTUpM7Wbw3g9M4',
    appId: '1:1083534585329:web:d4bc6fcd739c70c3f4e850',
    messagingSenderId: '1083534585329',
    projectId: 'neummuk-ver2',
    authDomain: 'neummuk-ver2.firebaseapp.com',
    storageBucket: 'neummuk-ver2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeyEQj0yadN7p9SIYpJimz4S9KxujlN6Q',
    appId: '1:1083534585329:android:dec0de7c395ebf9af4e850',
    messagingSenderId: '1083534585329',
    projectId: 'neummuk-ver2',
    storageBucket: 'neummuk-ver2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nFLzaw6GkVBKxKVQSM0u987xRKxo3W0',
    appId: '1:1083534585329:ios:1a2820806c0fbfb2f4e850',
    messagingSenderId: '1083534585329',
    projectId: 'neummuk-ver2',
    storageBucket: 'neummuk-ver2.firebasestorage.app',
    iosBundleId: 'com.example.neummukVer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-nFLzaw6GkVBKxKVQSM0u987xRKxo3W0',
    appId: '1:1083534585329:ios:1a2820806c0fbfb2f4e850',
    messagingSenderId: '1083534585329',
    projectId: 'neummuk-ver2',
    storageBucket: 'neummuk-ver2.firebasestorage.app',
    iosBundleId: 'com.example.neummukVer2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGnrcIEVU-p0W7mygzipTUpM7Wbw3g9M4',
    appId: '1:1083534585329:web:d4bc6fcd739c70c3f4e850',
    messagingSenderId: '1083534585329',
    projectId: 'neummuk-ver2',
    authDomain: 'neummuk-ver2.firebaseapp.com',
    storageBucket: 'neummuk-ver2.firebasestorage.app',
  );

}